### ISSUE TITLE
Schiphollijn: Rijweg R3 - RB2 wordt niet goed afgereden

### ISSUE THREAD

**Issue by doosterhuis** [dgoedkoop/stwsim#5]
Bij het afrijden van de rijweg R3 - RB2 blijft wisselsectie 1301B groen.

**Comment by dgoedkoop** [comment]
Bij deze rijweg zit er een fout in de simulatiedata. De secties waaruit de rijweg bestaat staan niet in de goede volgorde, zodat de volgordedwang een foutmelding geeft en de sectie inderdaad niet wordt vrijgegeven. Zal z.s.m. een aangepaste versie uploaden.
