### ISSUE TITLE
Schiphollijn: kruising Hfd wordt niet juist weergegeven

### ISSUE THREAD

**Issue by doosterhuis** [dgoedkoop/stwsim#6]
De kruising tussen wissels 1123B/1123A en 1127/1125 wordt niet volledig gekleurd bij het instellen van een rijweg of bij het passeren van een trein. Vermoedelijk het gevolg van de bugfix van de kruisingen in versie 1.1.1RC.

**Comment by dgoedkoop** [comment]
Opgelost.
